Config = {}

Config.Debug = false
Config.MenuKey = 'F6'
Config.AttackKey = 'G'
Config.MaxSpawnedPets = 1
Config.Menu = {
    top = '18px',
    right = '18px',
    width = 392,
}

Config.CallCooldown = 1200
Config.ActionCooldown = 1200
Config.AttackCooldown = 8000
Config.FollowDistance = 2.2
Config.WalkFollowDistance = 1.4
Config.TeleportDistance = 42.0
Config.InteractDistance = 3.0
Config.PetsEnterVehicles = true
Config.AttackPlayers = false
Config.AttackTimeout = 16000
Config.ModelLoadTimeout = 8000

Config.Decay = {
    interval = 60,
    hunger = 1.1,
    thirst = 1.4,
    happiness = 0.45,
    healthWhenStarving = 2.2,
    offlineDecay = true,
    offlineDeath = false,
    maxOfflineSeconds = 86400,
}

Config.Needs = {
    feedAmount = 42,
    waterAmount = 48,
    petHappiness = 14,
    walkHappinessPerTick = 4,
    walkHungerCost = 3,
    walkThirstCost = 4,
    walkTick = 30,
    reviveHealth = 55,
    reviveHunger = 50,
    reviveThirst = 50,
    reviveHappiness = 35,
    bondPet = 4,
    bondFeed = 3,
    bondWalk = 5,
    bondPerLevel = 100,
    maxLevel = 10,
}

Config.Leash = {
    length = 3.6,
    type = 5,
}

Config.Target = {
    useOxTarget = true,
}

Config.Shop = {
    enabled = true,
    useCustomUI = true,
    name = 'Companion Emporium',
    ped = `s_m_m_linecook`,
    scenario = 'WORLD_HUMAN_CLIPBOARD',
    coords = vec4(563.18, 2752.93, 42.88, 187.0),
    currency = {
        type = 'ox_inventory',
        item = 'money',
    },
    blip = {
        enabled = true,
        sprite = 273,
        color = 5,
        scale = 0.85,
        label = 'Companion Emporium',
    },
}

Config.K9 = {
    attackPlayers = true,
    attackCooldown = 4500,
    searchCooldown = 6000,
    guardRadius = 8.0,
    requireJob = false,
    jobs = { 'police', 'sheriff', 'lspd', 'bcso', 'sasp' },
}

Config.Categories = {
    { id = 'k9', label = 'Police K9' },
    { id = 'dogs', label = 'Dogs' },
    { id = 'puppies', label = 'Puppies' },
    { id = 'cats', label = 'Cats' },
    { id = 'farm', label = 'Farm' },
    { id = 'exotic', label = 'Exotic' },
    { id = 'wild', label = 'Wild' },
    { id = 'special', label = 'Special' },
    { id = 'supplies', label = 'Supplies' },
}

local COLLAR_DOG = { bone = 39317, offset = vec3(0.0, 0.0, -0.03), rot = vec3(0.0, 90.0, 0.0) }
local COLLAR_SMALL = { bone = 39317, offset = vec3(0.0, 0.02, -0.02), rot = vec3(0.0, 90.0, 0.0) }
local COLLAR_LARGE = { bone = 39317, offset = vec3(0.0, 0.02, -0.04), rot = vec3(0.0, 90.0, 0.0) }
local COLLAR_BODY = { bone = 24818, offset = vec3(0.0, 0.12, 0.0), rot = vec3(0.0, 90.0, 0.0) }

-- item name -> companion definition
-- canAttack: dogs, wolves, bears, honey badgers, and the robot can be sent after a target
-- dogAnims: Franklin/Chop petting clips (canine models only)
Config.Animals = {
    pet_chop = {
        label = 'Chop',
        model = `A_C_Chop`,
        modelName = 'A_C_Chop',
        category = 'dogs',
        rarity = 'rare',
        price = 12500,
        weight = 4200,
        canAttack = true,
        dogAnims = true,
        textures = 0,
        sitScenario = 'WORLD_DOG_SITTING_ROTTWEILER',
        barkScenario = 'WORLD_DOG_BARKING_ROTTWEILER',
        scale = 1.0,
        collar = COLLAR_LARGE,
        description = 'A department-grade rottweiler. Bite work first, loyalty always.',
    },
    pet_husky = {
        label = 'Husky',
        model = `A_C_Husky_2`,
        modelName = 'A_C_Husky_2',
        category = 'dogs',
        rarity = 'uncommon',
        price = 8750,
        weight = 3600,
        canAttack = true,
        dogAnims = true,
        textures = 1,
        sitScenario = 'WORLD_DOG_SITTING_RETRIEVER',
        barkScenario = 'WORLD_DOG_BARKING_RETRIEVER',
        scale = 1.0,
        collar = COLLAR_DOG,
        description = 'A thick-coated northern working dog that never tires of a long walk.',
    },
    pet_retriever = {
        label = 'Retriever',
        model = `A_C_Retriever_2`,
        modelName = 'A_C_Retriever_2',
        category = 'dogs',
        rarity = 'uncommon',
        price = 8000,
        weight = 3400,
        canAttack = true,
        dogAnims = true,
        textures = 1,
        sitScenario = 'WORLD_DOG_SITTING_RETRIEVER',
        barkScenario = 'WORLD_DOG_BARKING_RETRIEVER',
        scale = 1.0,
        collar = COLLAR_DOG,
        description = 'A golden-hearted gundog. Soft mouth, softer personality.',
    },
    pet_shepherd = {
        label = 'German Shepherd',
        model = `A_C_shepherd_2`,
        modelName = 'A_C_shepherd_2',
        category = 'dogs',
        rarity = 'uncommon',
        price = 9000,
        weight = 3800,
        canAttack = true,
        dogAnims = true,
        textures = 1,
        sitScenario = 'WORLD_DOG_SITTING_SHEPHERD',
        barkScenario = 'WORLD_DOG_BARKING_SHEPHERD',
        scale = 1.0,
        collar = COLLAR_DOG,
        description = 'The standard police shepherd. Tracks, holds, and takes a suspect down on command.',
    },
    pet_dusa_doberman = {
        label = 'Dusa Doberman',
        model = `dusa_doberman`,
        modelName = 'dusa_doberman',
        category = 'dogs',
        rarity = 'rare',
        price = 9800,
        weight = 3700,
        canAttack = true,
        dogAnims = true,
        textures = 0,
        sitScenario = 'WORLD_DOG_SITTING_SHEPHERD',
        barkScenario = 'WORLD_DOG_BARKING_SHEPHERD',
        scale = 1.0,
        collar = COLLAR_DOG,
        description = 'A protection-line Doberman used for patrol and suspect apprehension.',
    },
    pet_westy = {
        label = 'West Highland Terrier',
        model = `a_c_westy_2`,
        modelName = 'a_c_westy_2',
        category = 'dogs',
        rarity = 'common',
        price = 4800,
        weight = 1400,
        canAttack = true,
        dogAnims = true,
        textures = 0,
        sitScenario = 'WORLD_DOG_SITTING_TERRIER',
        barkScenario = 'WORLD_DOG_BARKING_SMALL',
        scale = 1.0,
        collar = COLLAR_SMALL,
        description = 'A compact white terrier with a huge personality and a bigger bark.',
    },
    pet_poodle = {
        label = 'Poodle',
        model = `a_c_poodle_2`,
        modelName = 'a_c_poodle_2',
        category = 'dogs',
        rarity = 'uncommon',
        price = 5200,
        weight = 1800,
        canAttack = true,
        dogAnims = true,
        textures = 0,
        sitScenario = 'WORLD_DOG_SITTING_TERRIER',
        barkScenario = 'WORLD_DOG_BARKING_SMALL',
        scale = 1.0,
        collar = COLLAR_SMALL,
        description = 'An elegant companion with a cloud of curls and a clever streak.',
    },
    pet_sphynx = {
        label = 'Sphynx',
        model = `dusa_sphynx`,
        modelName = 'dusa_sphynx',
        category = 'cats',
        rarity = 'rare',
        price = 6500,
        weight = 800,
        canAttack = false,
        dogAnims = false,
        textures = 0,
        sitScenario = 'WORLD_CAT_SLEEPING_GROUND',
        barkScenario = nil,
        scale = 1.0,
        collar = COLLAR_SMALL,
        description = 'Hairless, warm, and wildly affectionate. A living velvet statue.',
    },
    pet_cane = {
        label = 'Cane Corso',
        model = `dusa_cane`,
        modelName = 'dusa_cane',
        category = 'dogs',
        rarity = 'rare',
        price = 11000,
        weight = 4500,
        canAttack = true,
        dogAnims = true,
        textures = 0,
        sitScenario = 'WORLD_DOG_SITTING_ROTTWEILER',
        barkScenario = 'WORLD_DOG_BARKING_ROTTWEILER',
        scale = 1.0,
        collar = COLLAR_LARGE,
        description = 'A heavy K9 mastiff. Holds ground, guards a perimeter, and does not back down.',
    },
    pet_bulldog = {
        label = 'English Bulldog',
        model = `dusa_englishbulldog`,
        modelName = 'dusa_englishbulldog',
        category = 'dogs',
        rarity = 'uncommon',
        price = 7500,
        weight = 3200,
        canAttack = true,
        dogAnims = true,
        textures = 0,
        sitScenario = 'WORLD_DOG_SITTING_ROTTWEILER',
        barkScenario = 'WORLD_DOG_BARKING_SMALL',
        scale = 1.0,
        collar = COLLAR_DOG,
        description = 'Wrinkled, stubborn, and unexpectedly charming on a short walk.',
    },
    pet_aussiepup = {
        label = 'Aussie Puppy',
        model = `a_c_aussiepup`,
        modelName = 'a_c_aussiepup',
        category = 'puppies',
        rarity = 'common',
        price = 4200,
        weight = 1200,
        canAttack = true,
        dogAnims = true,
        textures = 0,
        sitScenario = 'WORLD_DOG_SITTING_TERRIER',
        barkScenario = 'WORLD_DOG_BARKING_SMALL',
        scale = 1.0,
        collar = COLLAR_SMALL,
        description = 'A merle-coated ball of energy that will herd anything that moves.',
    },
    pet_dalmatian = {
        label = 'Dalmatian',
        model = `a_c_dalmatian`,
        modelName = 'a_c_dalmatian',
        category = 'dogs',
        rarity = 'uncommon',
        price = 8500,
        weight = 3300,
        canAttack = true,
        dogAnims = true,
        textures = 0,
        sitScenario = 'WORLD_DOG_SITTING_RETRIEVER',
        barkScenario = 'WORLD_DOG_BARKING_RETRIEVER',
        scale = 1.0,
        collar = COLLAR_DOG,
        description = 'Spotted, athletic, and born to ride shotgun with the fire crew.',
    },
    pet_dodo = {
        label = 'Dodo',
        model = `a_c_dodo`,
        modelName = 'a_c_dodo',
        category = 'exotic',
        rarity = 'epic',
        price = 18000,
        weight = 2200,
        canAttack = false,
        dogAnims = false,
        textures = 0,
        sitScenario = nil,
        barkScenario = nil,
        scale = 1.0,
        collar = COLLAR_BODY,
        description = 'A plump, flightless relic. Slow, curious, and completely unbothered.',
    },
    pet_fdpuppy = {
        label = 'Frenchie Puppy',
        model = `a_c_fdpuppy`,
        modelName = 'a_c_fdpuppy',
        category = 'puppies',
        rarity = 'common',
        price = 4500,
        weight = 1100,
        canAttack = true,
        dogAnims = true,
        textures = 0,
        sitScenario = 'WORLD_DOG_SITTING_TERRIER',
        barkScenario = 'WORLD_DOG_BARKING_SMALL',
        scale = 1.0,
        collar = COLLAR_SMALL,
        description = 'A snorty little bat-ear with more attitude than body weight.',
    },
    pet_husky_np = {
        label = 'Husky NP',
        model = `a_c_husky_np`,
        modelName = 'a_c_husky_np',
        category = 'dogs',
        rarity = 'uncommon',
        price = 8800,
        weight = 3600,
        canAttack = true,
        dogAnims = true,
        textures = 0,
        sitScenario = 'WORLD_DOG_SITTING_RETRIEVER',
        barkScenario = 'WORLD_DOG_BARKING_RETRIEVER',
        scale = 1.0,
        collar = COLLAR_DOG,
        description = 'A working husky used for tracking and cold-weather patrols.',
    },
    pet_lspd = {
        label = 'LSPD K9',
        model = `a_c_lspddog`,
        modelName = 'a_c_lspddog',
        category = 'dogs',
        rarity = 'rare',
        price = 14000,
        weight = 4000,
        canAttack = true,
        dogAnims = true,
        textures = 0,
        sitScenario = 'WORLD_DOG_SITTING_SHEPHERD',
        barkScenario = 'WORLD_DOG_BARKING_SHEPHERD',
        scale = 1.0,
        collar = COLLAR_DOG,
        description = 'LSPD issued K9. Search, guard, and takedown trained.',
    },
    pet_pit = {
        label = 'Pit Bull',
        model = `A_C_Pit_NP`,
        modelName = 'A_C_Pit_NP',
        category = 'dogs',
        rarity = 'uncommon',
        price = 9200,
        weight = 3500,
        canAttack = true,
        dogAnims = true,
        textures = 0,
        sitScenario = 'WORLD_DOG_SITTING_ROTTWEILER',
        barkScenario = 'WORLD_DOG_BARKING_ROTTWEILER',
        scale = 1.0,
        collar = COLLAR_DOG,
        description = 'A patrol pit used for holds and close-quarters takedowns.',
    },
    pet_pitpup = {
        label = 'Pit Bull Puppy',
        model = `a_c_pitbullpup`,
        modelName = 'a_c_pitbullpup',
        category = 'puppies',
        rarity = 'common',
        price = 4300,
        weight = 1300,
        canAttack = true,
        dogAnims = true,
        textures = 0,
        sitScenario = 'WORLD_DOG_SITTING_TERRIER',
        barkScenario = 'WORLD_DOG_BARKING_SMALL',
        scale = 1.0,
        collar = COLLAR_SMALL,
        description = 'A pocket tank with wrinkles, wiggles, and a lot of love to give.',
    },
    pet_raccoon = {
        label = 'Raccoon',
        model = `A_C_Raccoon_01`,
        modelName = 'A_C_Raccoon_01',
        category = 'exotic',
        rarity = 'uncommon',
        price = 7000,
        weight = 900,
        canAttack = false,
        dogAnims = false,
        textures = 0,
        sitScenario = nil,
        barkScenario = nil,
        scale = 1.0,
        collar = COLLAR_SMALL,
        description = 'A masked bandit that will steal snacks, hearts, and unattended tacos.',
    },
    pet_retriever_np = {
        label = 'Retriever NP',
        model = `A_C_Retriever_np`,
        modelName = 'A_C_Retriever_np',
        category = 'dogs',
        rarity = 'uncommon',
        price = 8200,
        weight = 3400,
        canAttack = true,
        dogAnims = true,
        textures = 0,
        sitScenario = 'WORLD_DOG_SITTING_RETRIEVER',
        barkScenario = 'WORLD_DOG_BARKING_RETRIEVER',
        scale = 1.0,
        collar = COLLAR_DOG,
        description = 'A detection retriever. Used for searches, articles, and suspect tracking.',
    },
    pet_rotpuppy = {
        label = 'Rottweiler Puppy',
        model = `a_c_rotpuppy`,
        modelName = 'a_c_rotpuppy',
        category = 'puppies',
        rarity = 'common',
        price = 4600,
        weight = 1500,
        canAttack = true,
        dogAnims = true,
        textures = 0,
        sitScenario = 'WORLD_DOG_SITTING_TERRIER',
        barkScenario = 'WORLD_DOG_BARKING_SMALL',
        scale = 1.0,
        collar = COLLAR_SMALL,
        description = 'A chubby rust-and-black pup that will grow into a serious guardian.',
    },
    pet_shepherd_np = {
        label = 'Shepherd NP',
        model = `a_c_shepherd_np`,
        modelName = 'a_c_shepherd_np',
        category = 'dogs',
        rarity = 'uncommon',
        price = 9100,
        weight = 3800,
        canAttack = true,
        dogAnims = true,
        textures = 0,
        sitScenario = 'WORLD_DOG_SITTING_SHEPHERD',
        barkScenario = 'WORLD_DOG_BARKING_SHEPHERD',
        scale = 1.0,
        collar = COLLAR_DOG,
        description = 'A sable patrol shepherd. Fast on a track and reliable on a bite command.',
    },
    pet_bostonpup = {
        label = 'Boston Terrier Puppy',
        model = `bostonterrier_puppy`,
        modelName = 'bostonterrier_puppy',
        category = 'puppies',
        rarity = 'common',
        price = 4000,
        weight = 1000,
        canAttack = true,
        dogAnims = true,
        textures = 0,
        sitScenario = 'WORLD_DOG_SITTING_TERRIER',
        barkScenario = 'WORLD_DOG_BARKING_SMALL',
        scale = 1.0,
        collar = COLLAR_SMALL,
        description = 'A tuxedo-clad spark plug. Small, tuxedoed, and always ready to play.',
    },
    pet_boxerpup = {
        label = 'Boxer Puppy',
        model = `boxerpuppy`,
        modelName = 'boxerpuppy',
        category = 'puppies',
        rarity = 'common',
        price = 4100,
        weight = 1200,
        canAttack = true,
        dogAnims = true,
        textures = 0,
        sitScenario = 'WORLD_DOG_SITTING_TERRIER',
        barkScenario = 'WORLD_DOG_BARKING_SMALL',
        scale = 1.0,
        collar = COLLAR_SMALL,
        description = 'A wrinkly acrobat with spring-loaded hind legs and a goofy grin.',
    },
    pet_capybara = {
        label = 'Capybara',
        model = `bugcapybara`,
        modelName = 'bugcapybara',
        category = 'exotic',
        rarity = 'epic',
        price = 16000,
        weight = 5500,
        canAttack = false,
        dogAnims = false,
        textures = 0,
        sitScenario = nil,
        barkScenario = nil,
        scale = 1.0,
        collar = COLLAR_BODY,
        description = 'The world\'s most relaxed roommate. Semi-aquatic and endlessly chill.',
    },
    pet_piglet = {
        label = 'Piglet',
        model = `bugpiglet`,
        modelName = 'bugpiglet',
        category = 'farm',
        rarity = 'common',
        price = 2800,
        weight = 1800,
        canAttack = false,
        dogAnims = false,
        textures = 0,
        sitScenario = nil,
        barkScenario = nil,
        scale = 1.0,
        collar = COLLAR_SMALL,
        description = 'A tiny pink tank that will follow you for treats and belly rubs.',
    },
    pet_blackbear = {
        label = 'Black Bear',
        model = `c3d_blackbear`,
        modelName = 'c3d_blackbear',
        category = 'wild',
        rarity = 'legendary',
        price = 22000,
        weight = 8000,
        canAttack = true,
        dogAnims = false,
        textures = 0,
        sitScenario = nil,
        barkScenario = nil,
        scale = 1.0,
        collar = COLLAR_LARGE,
        description = 'A forest heavyweight. Keep it fed, keep it happy, keep it leashed.',
    },
    pet_donkey = {
        label = 'Donkey',
        model = `c3d_donkey`,
        modelName = 'c3d_donkey',
        category = 'farm',
        rarity = 'uncommon',
        price = 6500,
        weight = 7000,
        canAttack = false,
        dogAnims = false,
        textures = 0,
        sitScenario = nil,
        barkScenario = nil,
        scale = 1.0,
        collar = COLLAR_BODY,
        description = 'Stubborn, sure-footed, and surprisingly affectionate once it trusts you.',
    },
    pet_goat = {
        label = 'Goat',
        model = `c3d_goat`,
        modelName = 'c3d_goat',
        category = 'farm',
        rarity = 'common',
        price = 3500,
        weight = 4000,
        canAttack = false,
        dogAnims = false,
        textures = 0,
        sitScenario = nil,
        barkScenario = nil,
        scale = 1.0,
        collar = COLLAR_BODY,
        description = 'A professional climber and amateur demolition expert. Watch your plants.',
    },
    pet_honeybadger = {
        label = 'Honey Badger',
        model = `c3d_honeybadger`,
        modelName = 'c3d_honeybadger',
        category = 'wild',
        rarity = 'epic',
        price = 14500,
        weight = 1800,
        canAttack = true,
        dogAnims = false,
        textures = 0,
        sitScenario = nil,
        barkScenario = nil,
        scale = 1.0,
        collar = COLLAR_SMALL,
        description = 'Fearless, stocky, and allergic to backing down. Give it space.',
    },
    pet_wolf = {
        label = 'Wolf',
        model = `c3d_lobo`,
        modelName = 'c3d_lobo',
        category = 'wild',
        rarity = 'epic',
        price = 17000,
        weight = 4200,
        canAttack = true,
        dogAnims = false,
        textures = 0,
        sitScenario = nil,
        barkScenario = 'WORLD_COYOTE_HOWL',
        scale = 1.0,
        collar = COLLAR_DOG,
        description = 'A timber wolf with a low howl and a stare that means business.',
    },
    pet_pig = {
        label = 'Pig',
        model = `c3d_pig`,
        modelName = 'c3d_pig',
        category = 'farm',
        rarity = 'common',
        price = 3800,
        weight = 5000,
        canAttack = false,
        dogAnims = false,
        textures = 1,
        sitScenario = nil,
        barkScenario = nil,
        scale = 1.0,
        collar = COLLAR_BODY,
        description = 'A full-grown farm hog. Smart, hungry, and excellent at finding snacks.',
    },
    pet_skunk = {
        label = 'Skunk',
        model = `c3d_skunk`,
        modelName = 'c3d_skunk',
        category = 'exotic',
        rarity = 'uncommon',
        price = 5500,
        weight = 700,
        canAttack = false,
        dogAnims = false,
        textures = 0,
        sitScenario = nil,
        barkScenario = nil,
        scale = 1.0,
        collar = COLLAR_SMALL,
        description = 'Striped, sweet, and best enjoyed from a polite distance.',
    },
    pet_turkey = {
        label = 'Turkey',
        model = `c3d_turkey`,
        modelName = 'c3d_turkey',
        category = 'farm',
        rarity = 'common',
        price = 2400,
        weight = 1600,
        canAttack = false,
        dogAnims = false,
        textures = 0,
        sitScenario = nil,
        barkScenario = nil,
        scale = 1.0,
        collar = COLLAR_BODY,
        description = 'A gobbling parade float. Surprisingly proud for a bird that cannot fly far.',
    },
    pet_chowchow = {
        label = 'Chow Chow',
        model = `chowchow`,
        modelName = 'chowchow',
        category = 'dogs',
        rarity = 'uncommon',
        price = 7800,
        weight = 3100,
        canAttack = true,
        dogAnims = true,
        textures = 0,
        sitScenario = 'WORLD_DOG_SITTING_RETRIEVER',
        barkScenario = 'WORLD_DOG_BARKING_RETRIEVER',
        scale = 1.0,
        collar = COLLAR_DOG,
        description = 'A lion-maned aristocrat with a blue-black tongue and a serious face.',
    },
    pet_dalpup = {
        label = 'Dalmatian Puppy',
        model = `dal_puppy`,
        modelName = 'dal_puppy',
        category = 'puppies',
        rarity = 'common',
        price = 4400,
        weight = 1100,
        canAttack = true,
        dogAnims = true,
        textures = 0,
        sitScenario = 'WORLD_DOG_SITTING_TERRIER',
        barkScenario = 'WORLD_DOG_BARKING_SMALL',
        scale = 1.0,
        collar = COLLAR_SMALL,
        description = 'A spotted spark. Fast, curious, and already practicing the firehouse pose.',
    },
    pet_doberman = {
        label = 'Doberman',
        model = `doberman`,
        modelName = 'doberman',
        category = 'dogs',
        rarity = 'rare',
        price = 9600,
        weight = 3700,
        canAttack = true,
        dogAnims = true,
        textures = 0,
        sitScenario = 'WORLD_DOG_SITTING_SHEPHERD',
        barkScenario = 'WORLD_DOG_BARKING_SHEPHERD',
        scale = 1.0,
        collar = COLLAR_DOG,
        description = 'A patrol Doberman. Search, guard, and takedown certified.',
    },
    pet_dachshund = {
        label = 'Longhair Dachshund',
        model = `poprplonghairweiner`,
        modelName = 'poprplonghairweiner',
        category = 'dogs',
        rarity = 'uncommon',
        price = 5600,
        weight = 1400,
        canAttack = true,
        dogAnims = true,
        textures = 0,
        sitScenario = 'WORLD_DOG_SITTING_TERRIER',
        barkScenario = 'WORLD_DOG_BARKING_SMALL',
        scale = 1.0,
        collar = COLLAR_SMALL,
        description = 'A silky hot-dog with the heart of a hunter and the legs of a commuter.',
    },
    pet_reindeer = {
        label = 'Reindeer',
        model = `reindeer`,
        modelName = 'reindeer',
        category = 'exotic',
        rarity = 'legendary',
        price = 20000,
        weight = 7500,
        canAttack = false,
        dogAnims = false,
        textures = 0,
        sitScenario = nil,
        barkScenario = nil,
        scale = 1.0,
        collar = COLLAR_BODY,
        description = 'Antlers, winter coat, and a calm that belongs on a holiday card.',
    },
    pet_robot = {
        label = 'Zathura',
        model = `Robot_Zathura`,
        modelName = 'Robot_Zathura',
        category = 'special',
        rarity = 'legendary',
        price = 25000,
        weight = 3000,
        canAttack = true,
        dogAnims = false,
        pedType = 4,
        textures = 0,
        sitScenario = nil,
        barkScenario = nil,
        scale = 1.0,
        collar = COLLAR_DOG,
        description = 'A compact companion automaton. No kibble required. Attitude optional.',
    },
    pet_yorkie = {
        label = 'Yorkshire Terrier Puppy',
        model = `yorkie_puppy`,
        modelName = 'yorkie_puppy',
        category = 'puppies',
        rarity = 'common',
        price = 3900,
        weight = 700,
        canAttack = true,
        dogAnims = true,
        textures = 0,
        sitScenario = 'WORLD_DOG_SITTING_TERRIER',
        barkScenario = 'WORLD_DOG_BARKING_SMALL',
        scale = 1.0,
        collar = COLLAR_SMALL,
        description = 'A silk-haired scrap of confidence that believes it owns the block.',
    },
}

local K9_TRAITS = { attack = true, search = true, guard = true }
Config.K9Units = {
    'pet_lspd',
    'pet_shepherd',
    'pet_shepherd_np',
    'pet_doberman',
    'pet_dusa_doberman',
    'pet_cane',
    'pet_pit',
    'pet_chop',
    'pet_retriever_np',
    'pet_husky_np',
}

for i = 1, #Config.K9Units do
    local animal = Config.Animals[Config.K9Units[i]]
    if animal then
        animal.category = 'k9'
        animal.k9 = true
        animal.canAttack = true
        animal.k9Traits = K9_TRAITS
    end
end

Config.Supplies = {
    pet_food = {
        label = 'Premium Kibble',
        price = 25,
        weight = 200,
        stack = true,
        description = 'Slow-baked kibble that fills the bowl and the bond meter.',
    },
    pet_water = {
        label = 'Fresh Water',
        price = 20,
        weight = 200,
        stack = true,
        description = 'Clean drinking water. Keep a few bottles on you for long walks.',
    },
    pet_collar = {
        label = 'Leather Collar',
        price = 150,
        weight = 80,
        stack = true,
        description = 'A fitted collar. Required before you can clip on a leash.',
    },
    pet_leash = {
        label = 'Walking Leash',
        price = 125,
        weight = 120,
        stack = false,
        description = 'Keep this in your inventory to walk a collared companion.',
    },
    pet_revive = {
        label = 'Revive Kit',
        price = 750,
        weight = 250,
        stack = true,
        description = 'Field medicine for a companion that collapsed from injury or neglect.',
    },
}

Config.SupplyItems = {
    food = 'pet_food',
    water = 'pet_water',
    collar = 'pet_collar',
    leash = 'pet_leash',
    revive = 'pet_revive',
}

Config.ShopItems = {}

local function pushShopItem(name, price)
    Config.ShopItems[#Config.ShopItems + 1] = { name = name, price = price }
end

local orderedAnimals = {}
for name, animal in pairs(Config.Animals) do
    orderedAnimals[#orderedAnimals + 1] = { name = name, animal = animal }
end
table.sort(orderedAnimals, function(a, b)
    if a.animal.category == b.animal.category then
        return a.animal.price < b.animal.price
    end
    return a.animal.category < b.animal.category
end)
for i = 1, #orderedAnimals do
    pushShopItem(orderedAnimals[i].name, orderedAnimals[i].animal.price)
end

local supplyOrder = { 'pet_food', 'pet_water', 'pet_collar', 'pet_leash', 'pet_revive' }
for i = 1, #supplyOrder do
    local name = supplyOrder[i]
    pushShopItem(name, Config.Supplies[name].price)
end

Config.Anims = {
    petOwner = { dict = 'creatures@rottweiler@tricks@', clip = 'petting_franklin', duration = 3500 },
    petDog = { dict = 'creatures@rottweiler@tricks@', clip = 'petting_chop', duration = 3500 },
    feedOwner = { dict = 'mp_common', clip = 'givetake1_a', duration = 1800 },
}
