--[[
    Copy these entries into ox_inventory/data/items.lua
    Copy images from install/images/ into ox_inventory/web/images/
]]

--[[
    ['pet_rottweiler'] = {
        label = 'Rottweiler',
        weight = 4000,
        stack = false,
        close = true,
        consume = 0,
        server = { export = 'djfivem-pets.usePet' },
    },
    ['pet_shepherd'] = {
        label = 'Shepherd',
        weight = 3800,
        stack = false,
        close = true,
        consume = 0,
        server = { export = 'djfivem-pets.usePet' },
    },
    ['pet_husky'] = {
        label = 'Husky',
        weight = 3600,
        stack = false,
        close = true,
        consume = 0,
        server = { export = 'djfivem-pets.usePet' },
    },
    ['pet_retriever'] = {
        label = 'Retriever',
        weight = 3400,
        stack = false,
        close = true,
        consume = 0,
        server = { export = 'djfivem-pets.usePet' },
    },
    ['pet_pug'] = {
        label = 'Pug',
        weight = 1600,
        stack = false,
        close = true,
        consume = 0,
        server = { export = 'djfivem-pets.usePet' },
    },
    ['pet_poodle'] = {
        label = 'Poodle',
        weight = 1800,
        stack = false,
        close = true,
        consume = 0,
        server = { export = 'djfivem-pets.usePet' },
    },
    ['pet_chop'] = {
        label = 'Chop',
        weight = 4200,
        stack = false,
        close = true,
        consume = 0,
        server = { export = 'djfivem-pets.usePet' },
    },
    ['pet_cat'] = {
        label = 'Cat',
        weight = 900,
        stack = false,
        close = true,
        consume = 0,
        server = { export = 'djfivem-pets.usePet' },
    },
    ['pet_rabbit'] = {
        label = 'Rabbit',
        weight = 600,
        stack = false,
        close = true,
        consume = 0,
        server = { export = 'djfivem-pets.usePet' },
    },
    ['pet_pig'] = {
        label = 'Pig',
        weight = 5000,
        stack = false,
        close = true,
        consume = 0,
        server = { export = 'djfivem-pets.usePet' },
    },
    ['pet_monkey'] = {
        label = 'Monkey',
        weight = 2500,
        stack = false,
        close = true,
        consume = 0,
        server = { export = 'djfivem-pets.usePet' },
    },
    ['pet_coyote'] = {
        label = 'Coyote',
        weight = 3200,
        stack = false,
        close = true,
        consume = 0,
        server = { export = 'djfivem-pets.usePet' },
    },
    ['pet_mtlion'] = {
        label = 'Mountain Lion',
        weight = 4500,
        stack = false,
        close = true,
        consume = 0,
        server = { export = 'djfivem-pets.usePet' },
    },
    ['pet_food'] = {
        label = 'Pet Food',
        weight = 200,
        stack = true,
        close = true,
        consume = 0,
        server = { export = 'djfivem-pets.useFood' },
    },
    ['pet_water'] = {
        label = 'Pet Water',
        weight = 200,
        stack = true,
        close = true,
        consume = 0,
        server = { export = 'djfivem-pets.useWater' },
    },
    ['pet_collar'] = {
        label = 'Pet Collar',
        weight = 80,
        stack = true,
        close = true,
        consume = 0,
        server = { export = 'djfivem-pets.useCollar' },
    },
    ['pet_leash'] = {
        label = 'Pet Leash',
        weight = 120,
        stack = false,
        close = true,
        consume = 0,
        server = { export = 'djfivem-pets.useLeash' },
    },
    ['pet_revive'] = {
        label = 'Pet Revive Kit',
        weight = 250,
        stack = true,
        close = true,
        consume = 0,
        server = { export = 'djfivem-pets.useRevive' },
    },
]]

return {
    pet_rottweiler = { label = 'Rottweiler', weight = 4000, stack = false, close = true, consume = 0, server = { export = 'djfivem-pets.usePet' } },
    pet_shepherd = { label = 'Shepherd', weight = 3800, stack = false, close = true, consume = 0, server = { export = 'djfivem-pets.usePet' } },
    pet_husky = { label = 'Husky', weight = 3600, stack = false, close = true, consume = 0, server = { export = 'djfivem-pets.usePet' } },
    pet_retriever = { label = 'Retriever', weight = 3400, stack = false, close = true, consume = 0, server = { export = 'djfivem-pets.usePet' } },
    pet_pug = { label = 'Pug', weight = 1600, stack = false, close = true, consume = 0, server = { export = 'djfivem-pets.usePet' } },
    pet_poodle = { label = 'Poodle', weight = 1800, stack = false, close = true, consume = 0, server = { export = 'djfivem-pets.usePet' } },
    pet_chop = { label = 'Chop', weight = 4200, stack = false, close = true, consume = 0, server = { export = 'djfivem-pets.usePet' } },
    pet_cat = { label = 'Cat', weight = 900, stack = false, close = true, consume = 0, server = { export = 'djfivem-pets.usePet' } },
    pet_rabbit = { label = 'Rabbit', weight = 600, stack = false, close = true, consume = 0, server = { export = 'djfivem-pets.usePet' } },
    pet_pig = { label = 'Pig', weight = 5000, stack = false, close = true, consume = 0, server = { export = 'djfivem-pets.usePet' } },
    pet_monkey = { label = 'Monkey', weight = 2500, stack = false, close = true, consume = 0, server = { export = 'djfivem-pets.usePet' } },
    pet_coyote = { label = 'Coyote', weight = 3200, stack = false, close = true, consume = 0, server = { export = 'djfivem-pets.usePet' } },
    pet_mtlion = { label = 'Mountain Lion', weight = 4500, stack = false, close = true, consume = 0, server = { export = 'djfivem-pets.usePet' } },
    pet_food = { label = 'Pet Food', weight = 200, stack = true, close = true, consume = 0, server = { export = 'djfivem-pets.useFood' } },
    pet_water = { label = 'Pet Water', weight = 200, stack = true, close = true, consume = 0, server = { export = 'djfivem-pets.useWater' } },
    pet_collar = { label = 'Pet Collar', weight = 80, stack = true, close = true, consume = 0, server = { export = 'djfivem-pets.useCollar' } },
    pet_leash = { label = 'Pet Leash', weight = 120, stack = false, close = true, consume = 0, server = { export = 'djfivem-pets.useLeash' } },
    pet_revive = { label = 'Pet Revive Kit', weight = 250, stack = true, close = true, consume = 0, server = { export = 'djfivem-pets.useRevive' } },
}
